-- 1. Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS retailpulse;

-- 2. Select the database to make it the "active" schema
USE retailpulse;
SHOW TABLES;
SELECT * FROM cleaned_dataset;

-- ❓ Business Problem  :- Company does not know which category contributes most to revenue.
SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_dataset
GROUP BY category
ORDER BY total_revenue DESC;

-- 🚀 Key Insight: Revenue is heavily concentrated in Electronics at 480,210.81, 
-- which significantly outperforms other categories, while Outerwear contributes the least at just 18,558.00, 
-- indicating a substantial performance gap across the product portfolio. 
			
---- ❓ Business Problem  2:  Are discounts actually increasing purchase value?
SELECT 
    discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM cleaned_dataset
GROUP BY discount_applied;

-- 🚀 Key Insight: While total revenue is slightly higher when no discount is applied (502,562.72 vs. 492,207.59), 
-- applying a discount significantly increases the average purchase value from 180.19 to 217.69,
--  suggesting that discounts successfully encourage customers to spend more per transaction.

-- ❓ Business Problem : 3. What is the total revenue generated by male and female customer ? 
SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_dataset
GROUP BY gender
ORDER BY total_revenue DESC;

-- 🚀 Key Insight: Revenue is fairly distributed across all segments, with Male customers generating the highest revenue at 392,443.71,
-- followed closely by Female customers at 352,269.39, and the Other category contributing 250,057.21.
 
 -- ❓ Business Problem  4. Which customer used a discount but still spent more then the average purchase amount ?
SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM cleaned_dataset
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM cleaned_dataset)
ORDER BY purchase_amount DESC
LIMIT 10;
-- 🚀 Key Insight: Identifying high-value customers, such as customer 4977 who spent 1,499.76, 
-- reveals a segment of shoppers who utilize discounts but still consistently generate purchase amounts significantly above the average,
--  representing a prime target for loyalty-building programs.

-- ❓ Business Problem: 5. Top/Bottom 5 products with highest average review rating
-- Top 5
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM cleaned_dataset
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- ---- 🚀 Key Insight : The top-rated products show high customer satisfaction, led by Gloves with an average rating of 3.86,
--  followed closely by Sandals at 3.83, Boots at 3.81, Hat at 3.80, and T-shirt at 3.79.


-- Bottom 5
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM cleaned_dataset
GROUP BY item_purchased
ORDER BY avg_rating ASC
LIMIT 5;
-- ---- 🚀 Key Insight : Key Insight: The product with the lowest customer satisfaction is Phone with an average rating of 2.92,
--  followed by Watch at 3.08, Headphones at 3.11, Laptop at 3.15, and Bag at 3.16.
         
-- ❓ Business Problem: 6. Average purchase: Standard vs Express shipping
SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_dataset
GROUP BY shipping_type
ORDER BY total_revenue DESC;

--- Key Insight: Faster shipping methods appear to correlate with higher spending, 
-- as Express shipping leads with the highest average order value of 354.72 and total revenue of 426,730.45, 
-- while options like Free Shipping and Next Day Air have significantly lower average order values, approximately 60.46 and 58.62 respectively.


            
 --  Business Problem  7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_users,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_dataset
GROUP BY subscription_status
ORDER BY total_revenue DESC;

---- Key Insight: While non-subscribed customers generate a higher total revenue of 569,195.30 due to a larger user base, 
-- subscribed customers are significantly more valuable on an individual basis,
--  with a substantially higher average revenue per purchase of 269.86 compared to 163.89 for non-subscribers.         


--  ❓ Business Problem 8. Top 5 products with highest discount usage %
SELECT 
    item_purchased,
    COUNT(*) AS total_sold,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS times_discounted,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_usage_percent
FROM cleaned_dataset
GROUP BY item_purchased
ORDER BY discount_usage_percent DESC
LIMIT 5;

----- Key Insight: The products with the highest reliance on discounts are led by Laptop at 52.86%, 
-- followed by Headphones at 51.81%, Sneakers at 50.70%, Phone at 50.59%, and Hat at 50.33%, 
-- highlighting that these items are frequently purchased using promotional offers.

            
-- ❓ Business Problem 9. Segment customer into new, returning and loyal based on their total number of previous purchase, 
-- and show the count of each segment.
SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM cleaned_dataset
GROUP BY CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END;
    
---- Key Insight: The customer base is predominantly composed of Loyal Customers with a count of 3,116,
--  significantly outnumbering Returning Customers at 1,373 and New Customers at 561, 
--  which indicates a strong base of long-term engagement with the brand.
 
            
-- ❓ Business Problem: 10. What are the top 3 most purchased products within each category ?
WITH CategoryRanking AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM cleaned_dataset
    GROUP BY category, item_purchased
)
SELECT * FROM CategoryRanking WHERE rnk <= 3;

-- Key Insight: Identifying the top 3 most purchased items per category reveals clear volume leaders, 
-- such as Shirt in Clothing (370 purchases), Shoes in Footwear (305 purchases), Jewelry in Accessories (180 purchases), 
-- and Phone in Electronics (170 purchases), which can directly inform inventory and marketing strategies.
            
-- ❓ Business Problem: 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
                                        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
                                        ELSE 'Normal Buyers'
                                    END), 2) AS percentage
FROM cleaned_dataset
GROUP BY CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END, subscription_status;

-- 🚀 Key Insight: Interestingly, Normal Buyers show a higher propensity to subscribe at 37.25% compared to Repeat Buyers, 
-- of whom only 29.64% have a subscription, suggesting that current subscription incentives may be less 
-- effective at retaining highly active repeat customers.
		
            
-- ❓ Business Problem: 12. What is the revenue contribution of each age group ? 
SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_dataset
GROUP BY CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END
ORDER BY total_revenue DESC;

--- Key Insight: The 51+ age group is the highest revenue contributor at 399,214.36, followed by the 36-50 age group at 266,355.41,
--  the 26-35 age group at 178,098.38, and the 18-25 age group at 151,102.15, 
--  demonstrating that older demographics provide the most significant share of total revenue.


