-- 1. Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS retailpulse;

-- 2. Select the database to make it the "active" schema
USE retailpulse;

-- 3. Check if the table exists before querying it
-- (If you get an error here, it means you haven't imported your data yet)
SELECT * FROM merged;


-- - 1. Which category generates highest revenue?
SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM merged
GROUP BY category
ORDER BY total_revenue DESC;

-- ❓ Business Problem :- Company does not know which category contributes most to revenue.


-- 🚀 Impact :- 
			 -- Helps prioritize high-performing categories
			 -- Optimizes inventory planning
			 -- Improves marketing ROI
             
-- 2. Are discounts actually increasing purchase value?

SELECT 
    discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM merged
GROUP BY discount_applied;

-- ❓ Business Problem :- Discounts may reduce profit without increasing sales.


-- 🚀 Impact :- 
				-- --Identify effectiveness of discounts
-- 				--Reduce unnecessary discount costs
-- 				--Improve profit margins

-- 3. What is the total revenue generated by male and female customer ? 
SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM merged
GROUP BY gender
ORDER BY total_revenue DESC;


-- ❓ Business Problem :- Lack of understanding of revenue contribution by gender segments.

-- 🚀 Impact:- 
			-- Helps design targeted marketing campaigns
			-- Improves customer segmentation strategy
			-- Enhances personalization efforts
 
 
-- 4. Which customer used a discount but still spent more then the average purchase amount ?

SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM merged
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM merged)
ORDER BY purchase_amount DESC
LIMIT 10;

-- 5. Top/Bottom 5 products with highest average review rating

-- Top 5
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM merged
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Bottom 5
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM merged
GROUP BY item_purchased
ORDER BY avg_rating ASC
LIMIT 5;

-- ❓ Business Problem:- Company cannot identify high-spending customers who are also discount users.


-- 🚀 Impact:- 
			-- Identifies premium discount-sensitive customers
			-- Enables targeted discount campaigns
			-- Improves customer retention and revenue
            
-- 6. Average purchase: Standard vs Express shipping
SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM merged
GROUP BY shipping_type
ORDER BY total_revenue DESC;

-- ❓ Business Problem :- Unclear if faster shipping leads to higher spending.


-- 🚀 Impact
			-- Helps optimize shipping pricing strategy
			-- Encourages premium shipping adoption
			-- Increases average order value
            
 -- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_users,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM merged
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- ❓ Business Problem :- The effectiveness of subscription programs is unknown.

-- 🚀 Impact
			-- Validates subscription model performance
			-- Improves customer loyalty programs
			-- Increases customer lifetime value (CLV)           


-- 8. Top 5 products with highest discount usage %
SELECT 
    item_purchased,
    COUNT(*) AS total_sold,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS times_discounted,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_usage_percent
FROM merged
GROUP BY item_purchased
ORDER BY discount_usage_percent DESC
LIMIT 5;

-- ❓ Business Problem :- Some products may be overly dependent on discounts.

-- 🚀 Impact:- 
			-- Identifies discount-driven products
			-- Helps optimize pricing strategy
			-- Reduces profit margin loss 
            
-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, 
-- and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM merged
GROUP BY CASE 
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customers'
    END;
    


-- ❓ Business Problem :- Lack of customer segmentation leads to generic strategies.


-- 🚀 Impact:- 
			-- Enables personalized marketing
			-- Improves retention strategies
			-- Increases conversion rates  
            
-- 10. What are the top 3 most purchased products within each category ?

WITH CategoryRanking AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM MERGED
    GROUP BY category, item_purchased
)
SELECT * FROM CategoryRanking WHERE rnk <= 3;

-- ❓ Business Problem:- The company doesn’t know top-performing products within categories.


-- 🚀 Impact
			-- Improves product placement & recommendations
			-- Helps inventory optimization
			-- Increases sales through best-sellers
            
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
 
SELECT
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
                                        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
                                        ELSE 'Normal Buyers'
                                    END), 2) AS percentage
FROM merged
GROUP BY CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END, subscription_status;

-- ❓ Business Problem :- Unclear relationship between loyalty and subscription.

-- 🚀 Impact:- 
			-- Improves subscription targeting
			-- Increases conversion to paid programs
			-- increase customer retention strategy
            
-- 12. What is the revenue contribution of each age group ? 
SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM merged
GROUP BY CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END
ORDER BY total_revenue DESC;


-- ❓ Business Problem:- No visibility into which age group contributes most to revenue.

-- 🚀 Impact:-
			-- Enables age-based targeting
			-- Enhances marketing efficiency
